### ISSUE TITLE
I cannot reset my password for TreeBASE.

### ISSUE THREAD

**Issue by VikramMisra** [TreeBASE/treebase#273]
Hello,

I have forgotten my password and my username for TreeBASE.  So I went to the TreeBASE Password Request page and tried just entering my e-mail.  However, I had a page showing a "Java Uncaught Exception".

I would greatly appreciate your help in resolving this problem.

Thank you very much,
Vikram Misra

**Comment by bambergerson** [comment]
Dear Vikram Misra, dear colleagues,

has someone found the solution to this problem?
I would need to reset my password for my Gmail-mailing address, and I am having the same issue (see below) e.g. with Internet Explorer 11 and Mozilla Firefox 81.0.2.

I wrote to help@treebase.org several times but no response yet.

Help would be appreciated.

Best,
Sonja Bamberger



Error message:
> Uncaught Exception Encountered 
java.lang.IllegalStateException: Can't overwrite cause with com.sun.mail.smtp.SMTPSendFailedException: 550-5.7.1 Invalid credentials for relay [145.136.242.129]. The IP address you've 550-5.7.1 registered in your G Suite SMTP Relay service doesn't match domain of 550-5.7.1 the account this email is being sent from. If you are trying to relay 550-5.7.1 mail from a domain that isn't registered under your G Suite account 550-5.7.1 or has empty envelope-from, you must configure your mail server 550-5.7.1 either to use SMTP AUTH to identify the sending domain or to present 550-5.7.1 one of your domain names in the HELO or EHLO command. For more 550-5.7.1 information, please visit 550 5.7.1 https://support.google.com/a/answer/6140680#invalidcred b10sm22683wmc.24 - gsmtpat java.lang.Throwable.initCause(Throwable.java:456)at javax.mail.MessagingException.setNextException(MessagingException.java:48)at javax.mail.Transport.send(Transport.java:109)at javax.mail.Transport.send(Transport.java:48)at org.cipres.treebase.web.controllers.PasswordFormController.onSubmit(PasswordFormController.java:134)at org.springframework.web.servlet.mvc.SimpleFormController.processFormSubmission(SimpleFormController.java:267)at org.springframework.web.servlet.mvc.CancellableFormController.processFormSubmission(CancellableFormController.java:140)at org.springframework.web.servlet.mvc.AbstractFormController.handleRequestInternal(AbstractFormController.java:265)at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:858)at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:792)at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:476)at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:441)at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:143)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:164)at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:141)at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:90)at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:406)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.displaytag.filter.ResponseOverrideFilter.doFilter(ResponseOverrideFilter.java:125)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:75)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:119)at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:55)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:264)at org.acegisecurity.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:107)at org.acegisecurity.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:72)at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)at org.acegisecurity.ui.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:110)at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)at org.acegisecurity.wrapper.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:81)at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:217)at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:191)at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)at org.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:148)at org.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:90)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:185)at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:159)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2555)at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2544)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)at java.lang.Thread.run(Thread.java:748) Caused by: com.sun.mail.smtp.SMTPSendFailedException: 550-5.7.1 Invalid credentials for relay [145.136.242.129]. The IP address you've 550-5.7.1 registered in your G Suite SMTP Relay service doesn't match domain of 550-5.7.1 the account this email is being sent from. If you are trying to relay 550-5.7.1 mail from a domain that isn't registered under your G Suite account 550-5.7.1 or has empty envelope-from, you must configure your mail server 550-5.7.1 either to use SMTP AUTH to identify the sending domain or to present 550-5.7.1 one of your domain names in the HELO or EHLO command. For more 550-5.7.1 information, please visit 550 5.7.1 https://support.google.com/a/answer/6140680#invalidcred n10sm39312wre.11 - gsmtpat com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:1388)at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:959)at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:583)at javax.mail.Transport.send(Transport.java:95)... 73 more Cookies: JSESSIONID=[42FA21096D1D4117754028543FFEB19B] __utmz=[216002130.1594222856.1.1.utmcsr] __utma=[216002130.1394456105.1594222856.1601459110.1603184996.3] __utmb=[216002130.6.10.1603184996] __utmc=[216002130] __utmt=[1]

**Comment by piel** [comment]
Indeed, the application was improperly built and the email functions don’t work. 

I’ve reset your password manually. I’ll email you separately. 

bp

**Comment by bambergerson** [comment]
Thanks a lot for the immediate response and password reset.
I could log in, everything works now!

**Comment by lneaves** [comment]
Hello I'm having the same problem. I've emailed the help@treebase.org, but having read the above I thought I it would be worth trying here. 
Thanks
Linda
